### PR TITLE
Windows x64

### PR DESCRIPTION
**Pull request by kevinmartin**
APM now supports x64. Atom is putting x64 in beta now.

https://github.com/atom/atom/pull/13135

### CODE REVIEW

**Comment by KevinMartin** [comment]
There seems to be some sort of build issue with AppVeyor. Possibly related to #3043 and https://github.com/nylas/N1/commit/e89fd364b4706b4a0d9972a1c4ce2fa131eaa4c6

**Comment by bengotow** [comment]
Hey! Thanks for submitting this - do you know of any major benefits to shipping 64-bit apps on Windows? Not questioning this effort or anything, I'm just honestly not sure. We've put off getting 64 bit support working because everyone seemed OK using the 32-bit version and N1 doesn't use enough memory to need the 64-bit address space.

**Comment by KevinMartin** [comment]
Maybe a default install won't need the 64-bit address space, but when you add multiple plugins and need to search through hundreds of contacts/threads/emails/etc, there should be some benefit.

Atom team had a similar stance, but realized it was important, because most people don't use the default installation without plugins.

**Comment by KevinMartin** [comment]
@bengotow the AppVeyor CI test is passing now.

**Comment by Stanzilla** [comment]
Will this get merged?

**Comment by KevinMartin** [comment]
Doubtful since the architecture for Nylas Mail has changed from Nylas N1/Pro

**Pull request closed without merging**
